services:

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: job4j_devops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"