[versions]
assertj = "3.24.2"
lombok = "1.18.36"
junit-jupiter = "5.10.0"

[libraries]
assertj = {module = "org.assertj:assertj-core", version.ref = "assertj"}
lombok = {module = "org.projectlombok:lombok", version.ref = "lombok"}
springBootStarterWeb = {module = "org.springframework.boot:spring-boot-starter-web"}
springBootStarterTest = {module = "org.springframework.boot:spring-boot-starter-test"}
junitPlatform = {module = "org.junit.platform:junit-platform-launcher"}
junitJupiter = {module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter"}